apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tax-calculator-pipeline-run
spec:
  pipelineRef:
    name: tax-calculator-pipeline
  params:
    - name: some-param
      value: some-value
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tax-calculator-pvc
